/* This file is auto-generated by Convex. Do not edit manually. */

declare module "convex/_generated/api" {
  export * from "../_generated/api.js";
}
declare module "convex/_generated/server" {
  export * from "../_generated/server.js";
}
declare module "convex/_generated/dataModel" {
  export * from "../_generated/dataModel.js";
}
